JuliaGraphics/Cairo.jl

src/Cairo.jl
test/runtests.jl

Previously we had (with the new tests)
```jl
Cairo.CairoContext must implement width
in width at no file
in anonymous at test.jl:90
in do_test at test.jl:50
in include at ./boot.jl:259
in include_from_node1 at ./loading.jl:267
in process_options at ./client.jl:308
in _start at ./client.jl:411
in width at no file
in anonymous at test.jl:90
in do_test at test.jl:50
in include at ./boot.jl:259
in include_from_node1 at ./loading.jl:267
in process_options at ./client.jl:308
in _start at ./client.jl:411
while loading /home/tim/.julia/v0.3/Cairo/test/runtests.jl, in expression starting on line 8
```
so Cairo was not living up to the promises made by Graphics.

Implement width and height for CairoContext

---

src/Cairo.jl

In working with Gtk (but not limited to) it's possible to get in calls or callbacks a cairo context as single pointer. This extends to the CairoContext by getting the surface information and adding a pango layout.

CairoContext from pointer only,

---

samples/sample_arc.jl
samples/sample_arc_negative.jl
samples/sample_clip.jl
samples/sample_clip_image.jl
samples/sample_copy_path.jl
samples/sample_curve_rectangle.jl
samples/sample_curve_to.jl
samples/sample_dash.jl
samples/sample_fill_and_stroke2.jl
samples/sample_fill_style.jl
samples/sample_gradient.jl
samples/sample_image.jl
samples/sample_imagepattern.jl
samples/sample_multi_segment_caps.jl
samples/sample_rounded_rectangle.jl
samples/sample_set_line_cap.jl
samples/sample_set_line_join.jl
samples/sample_text.jl
samples/sample_text_align_center.jl
samples/sample_text_extents.jl

The title more or less says it, you got quite many deprecation warnings running the examples on a 0.4, as the programs copied literally from c-code and had some whitespace in the function call.

To reduce deprecation warnings: some whitespace and Libc for strftime

---

src/Cairo.jl

suggest Pkg.build if deps.jl was not created successfully by BinDeps

better error message when bindeps fails

---

src/Cairo.jl
test/shape_functions.jl
test/test_speed.jl

I'm trying to add paint_with_alpha to Cairo.jl. This addition appears to work. Not sure how to add tests, but this works:
using Cairo
c = CairoRGBSurface(256,256)
cr = CairoContext(c)
save(cr)
set_source_rgb(cr, 0.8, 0.8, 0.8)    # light gray
rectangle(cr, 0.0, 0.0, 256.0, 256.0) # background
fill(cr)
restore(cr)
save(cr)
image = read_from_png(Pkg.dir("Cairo", "samples/data/", "mulberry.png"))
w = image.width
h = image.height
translate(cr, 128.0, 128.0)
rotate(cr, 45* pi/180)
scale(cr, 256.0/w, 256.0/h)
translate(cr, -0.5*w, -0.5*h)
set_source_surface(cr, image, 0, 0)
paint(cr)
restore(cr)
save(cr)
scale(cr, 256.0/w, 256.0/h)
set_source_surface(cr, image, 0, 0)
paint_with_alpha(cr)                         # defaults to 0.5
restore(cr)
move_to(cr, 0.0, 12.0)
set_source_rgb(cr, 0, 0, 0) …

Add paint_with_alpha()

---

README.md
samples/sample_rounded_rectangle.jl
src/Cairo.jl
test/runtests.jl

This overdue change simply allows one to create a `CairoSurface` in terms of a `Matrix{T}` where  `T` is `RGB24` or `ARGB32` (from ColorTypes.jl). This allows Cairo to infer the (Cairo) format without having to mess with extra arguments.
Also fixes a number of deprecations on julia-0.5.

Allow RGB24/ARGB32 eltype in CairoSurface; fix depwarns

---

src/Cairo.jl
test/runtests.jl

This is an attempt at resolving issue #141.
* Primary piece for solving #141 is line 126 of the new Cairo.jl.
* When only the pointer is provided the reference count is incremented which prevents deletion but provides the behavior that appears to have been desired.
* A test is added so that future changes will cause a failed test if they break this functionality for `CairoContext` objects.

Support creating CairoContext and CairoSurface objects from Ptr{Void}

---

src/Cairo.jl

see appveyor https://ci.appveyor.com/project/tkelman/cairo-jl/build/1.0.79/job/rni9sahayo0omppg
```
ERROR: LoadError: LoadError: MethodError: no method matching unsafe_wrap(::Type{Array}, ::Ptr{Float64}, ::Tuple{UInt32,Int32}, ::Bool)
Closest candidates are:
unsafe_wrap{T,N}(::Union{Type{Array{T,N}},Type{Array{T,N}},Type{Array}}, ::Ptr{T}, ::Tuple{Vararg{Int32,N}}, ::Bool)
unsafe_wrap{T}(::Union{Type{Array{T,1}},Type{Array{T,N}},Type{Array}}, ::Ptr{T}, ::Integer, ::Bool)
unsafe_wrap{N,I<:Integer}(::Type{T}, ::Ptr{T}, ::Tuple{Vararg{I<:Integer,N}}, ::Bool)
...
in convert_cairo_path_data(::Cairo.CairoPath) at C:\Users\Tony\.julia\v0.5\Cairo\src\Cairo.jl:625
in example_copy_path(::Cairo.CairoContext) at C:\Users\Tony\.julia\v0.5\Cairo\samples\sample_copy_path.jl:40
in include_from_node1 at …
```

Convert a dimension to Int to fix a 32 bit error

---

deps/build.jl

Compat version requirement should already be high enough.

Fix depwarn on 0.5 and 0.6 in build script

---

src/Cairo.jl

Change Array statements to `Vector/Matrix` equivalents, using `(Array{T}(dims)` form. Currently the deprecation warnings are making the Travis logs too long to display (the last one was 429,255 lines) :)

Remove deprecated Array(T,dims) syntax

---

src/Cairo.jl
test/test_speed.jl

i would add similar for gobject and pangocairo but there doesn't seem to be a way to query their version at runtime.

add unexported vars storing pango/cairo version literals

---

REQUIRE
src/constants.jl

The package is no longer tested on 0.3 and a new version will not be able to be registered without dropping 0.3 support anyway, so this bumps the REQUIRE to 0.4. I've also fixed the `typealias` depwarns on 0.6.

Fix a couple depwarns, bump REQUIRE to 0.4

---

deps/build.jl

Avoids deprecation warnings on Julia 0.6.
I tried to do the inner constructor syntax too but I only have access to the GitHub web UI at the moment and it kept crashing whenever I tried to make that change. 😕

Quote shell wildcards in the build process

---

src/Cairo.jl

This PR updates the deprecated type constructor syntax used for `CairoSurface` to the 0.4-0.6 compatible syntax. (Note that `@compat` is required for 0.4.)
Fixes the last remaining item in #176.

Update type constructor syntax

---

src/Cairo.jl
test/runtests.jl

A recent Cairo update seems to have caused troubles for ImageView due to `reset_transform` from `Graphics` not being imported. It's fixed by the `importall` on master; this just adds a test to make sure it doesn't regress.

Fix and add test for reset_transform

---

deps/build.jl

This doesn't work on v0.7 because `Pkg.installed` doesn't take a String anymore. While it could be fixed with Compat I propose to remove the check since the error message for `using Homebrew` is very similar and we don't do the check for windows. Homebrew is also in `REQUIRE` so it should be installed.

remove Homebrew check

---

deps/build.jl

@tkelman: Sorry for being too quick. Could you please review, merge this one and initiate a release if this fixed the issue with the from source builds.

Fix from source builds for Julia version < 1.0

---

.travis.yml
deps/build.jl

thanks to @affans
https://github.com/JuliaGraphics/Cairo.jl/issues/230#issuecomment-414886635

Fix Homebrew issues on 0.7 and 1.0

---

src/Cairo.jl
test/runtests.jl

This fixes #248 by holding a reference to the IO stream in the `CairoSurface` type. I made `CairoSurface` abstract and introduced three concrete types: `CairoSurfaceBase`. `CairoSurfaceImage` and `CairoSurfaceIOStream` since they hold different things and encoding this all into a single type gets a mess.

Redesign the CairoSurface type

---

src/Cairo.jl

In #216, `importall Graphics` was converted to a list of more specific imports, since `importall` was being deprecated. That list is not complete, however, as can be witnessed by
```
julia> import Cairo, Graphics
julia> filter(x -> getfield(Graphics, x) != getfield(Cairo, x),
intersect(names(Graphics), names(Cairo)))
8-element Array{Symbol,1}:
:clip_preserve              
:device_to_user!            
:device_to_user_distance!   
:rel_move_to                
:stroke_transformed         
:stroke_transformed_preserve
:user_to_device!            
:user_to_device_distance!   
julia> import Cairo, Graphics
```
One effect of this is that `text` function
```
function text(ctx::CairoContext, x::Real, y::Real, str::AbstractString;
halign::AbstractString = "left", valign::AbstractString = "bottom", …
```

Import missing functions from Graphics.

---

.travis.yml
deps/build.jl

discussed [here](https://github.com/JuliaGraphics/Cairo.jl/issues/271), and also on upstream glib [here](https://gitlab.gnome.org/GNOME/pango/issues/363), using `dlopen/dlclose` is not supported by glib, but is used by BinDeps; suggested in https://github.com/JuliaPackaging/BinDeps.jl/issues/397 and verified by `print(getpid())`, the build process is run in another pid, therefore not using `dlclose` may be ok, patched with the new build.jl: only patch for macos and only patch the current version of BinDeps (`occursin("ZEval",pathof(BinDeps))`)
julia: 0.6 removed in .travis.yml since pathof is not available there, feel free to disregard
temporary until maybe https://github.com/JuliaGraphics/Cairo.jl/pull/229 is finished?

temporary: patch segfault on mac

---

.travis.yml
appveyor.yml

I'm dropping Julia 1.1 as it is not supported any more, having being superseded by Julia 1.2, see https://discourse.julialang.org/t/julia-v1-2-0-has-been-released/27742

Run tests on Julia 0.7, 1.0, 1.2, 1.3

---

Project.toml

Once this merges, a new release would be nice.

Loosen upper bounds on Colors

---

Project.toml

I've tested this locally and it passes tests. In the Travis logs it's worth checking whether it actually uses this version, though.
We might want to install https://github.com/bcbi/CompatHelper.jl, though https://github.com/bcbi/CompatHelper.jl/issues/160 is pretty annoying. But since Cairo's dependencies are pretty minimal, I doubt it will be that much of a problem here (it comes up much more often in packages with lots of dependencies).

Support Colors 0.12

---

src/Cairo.jl
test/runtests.jl

Gtk.jl and other libraries have containers with fields that are
typed abstractly as `::CairoSurface`. This allows `width` and
`height` to be inferrable even for the abstract type.
It enforces an "interface" expected of all CairoSurface subtypes.

Make height and width inferrable for (abstract) CairoSurface

---

src/Cairo.jl

The estimated time savings upon first use is listed in the comment for each.
Not a big improvement, but it certainly doesn't hurt.

Add a few precompile directives

---

src/Cairo.jl
test/runtests.jl

Try to add support for Cairo's `cairo_image_surface_get_data`.
Added one test for new function.

Support for cairo_image_surface_get_data (#342)

---

Project.toml

Bumping up dependencies for very old versions. Perhaps this can be done more aggressively.
Does someone have views on Cairo, Pango, and Glib? In general those builds made a lot of improvements in the last few versions and it may be nice to set a new minimum. Example: https://github.com/JuliaGraphics/Cairo.jl/issues/363#issuecomment-2220273451

Update version to 1.1 in Project.toml
